### ISSUE TITLE
Metadata parsing not functional in Arch Linux, Gnome 3.20

### ISSUE THREAD

**Issue by pyriand3r** [tiliado/nuvola-app-spotify#10]
Hi,
i am using NuvolaPlayer 3 under Arch Linux x64 with Gnome 3.20 and the MPRIS-Plugin is not working properly with the spotify app. Gnome is not recognizing Nuvola-Spotify as a Music Player which means that media keys are useless and the MPRIS integration into the Gnome Desktop is not working. Other Nuvola Apps like the [Digitally Imported App](https://github.com/ItzBlitz98/nuvola-app-digitally-imported) are working correctly, are recognized and i can use control keys etc, so i think it's a problem in the spotify app.
Developer Tools inside Nuvola is not recognizing Playback either and playback controls are not working.

Nuvola Version: 3.10
Spotify App : 2.1

**Comment by fenryxo** [comment]
Hello @pyriand3r. Thanks for taking the time to report your issue. Unfortunately, I'm not able to reproduce it. Could you provide a debugging output from terminal? See [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines) for details.

Hi @thenyeguy, could you try to reproduce the issue?

**Comment by pyriand3r** [comment]
Hi,
I have cleaned the webkit cache for the spotify app by removing the folder ~/.cache/nuvolaplayer3/apps_data/spotify and i also removed the nuvola cache under ~/.cache/nuvolaplayer3/Cache. Result is, that the media keys are working again... also the debug output tells me that they are disabled? Also the developer tools are working again, showing the playing track and controls are working there.

I have created a gist with the debug output as told in the Bug Reporting Guidelines:
https://gist.github.com/pyriand3r/6ca26befa2b884746834dfaf10f3b56f

Still the MPRIS is not working correctly for Spotify, as there are no controls in the message tray...

**Comment by pyriand3r** [comment]
Just got another funky error :) Suddenly the spotify app started a second song from the playlist, so it played to songs simultaniously. Hitting the Pause Button on Spotify's UI stopped the song that was shown as playing, but the second song continued. I had to close nuvola completely to stop playback.

**Comment by fenryxo** [comment]
You can try to remove following directories:

* ~/.local/share/webkitgtk
* ~/.cache/webkit
* ~/.cache/webkitgt
* ~/.cache/nuvolaplayer3/apps_data/spotify/
* ~/.config/nuvolaplayer3/apps_data/spotify/
* ~/.local/share/nuvolaplayer3/apps_data/spotify/

If the issue persists, set `export DIORITE_LOG_IPC_SERVER="yes"` and `export DIORITE_LOG_MESSAGE_SERVER="yes"` environment variables, post a new debug output, which will be more detailed, and attach a screenshot of the web app with developoer's sidebar.

**Comment by pyriand3r** [comment]
I have deleted all folders but issue persists, so here is the extended debug output:

https://gist.github.com/pyriand3r/c2763e9519e5bd55262e59c7907c2b46

The Debug ouptut contains the start of nuvolaplayer, entering spotify app, starting a song, closing nuvolaplayer (It should not close completely but live on in the mpris control of gnome menu because a song plays but it stops completely as it again does not recognize that a song is playing).

**Comment by pyriand3r** [comment]
![spotify_dev](https://cloud.githubusercontent.com/assets/2619815/14987196/5025fba0-114f-11e6-9056-9a50c4755f31.png)

**Comment by pyriand3r** [comment]
Hello, i just wanted to inform you that i recently reformated my computer. Everything is new und shiny but the bug continue to exist. Sometimes the recognition of playing track works, most of the time not. And sometimes nuvola starts a second song and plays two simultaniously. Very annoying. 
Is there anything else i can do to nail down the issue?

**Comment by fenryxo** [comment]
> Sometimes the recognition of playing track works, most of the time not.

It is necessary to find out why it happens. Following console errors might give a clue. @thenyeguy, could you look at it?

`https://play.spotify.com/user/pyriand3r/playlist/0l8ljePVj0LnHrWsiK9ctN:4:163: CONSOLE ERROR ReferenceError: Can't find variable: jQuery
https://play.spotify.com/user/pyriand3r/playlist/0l8ljePVj0LnHrWsiK9ctN:12:11225: CONSOLE ERROR TypeError: null is not an object (evaluating 'player.getPlayerState')`

> And sometimes nuvola starts a second song and plays two simultaniously.

Could you create a new ticket for this issue? Thanks.

**Comment by thenyeguy** [comment]
Sorry for the delay. I've been busy, and had to set up a dev VM since I no longer have a linux box.

Unfortunately I can't seem to replicate this issue myself. From the logs, the best I can tell is the statements that are failing aren't actually in our code, but in Spotify's, since neither of those calls are ones the integration script makes. It's possible something we do in the script could be setting things up wrong, but I don't know how to go about looking into that without a way to repro myself. I'll poke at this little tomorrow evening and see if anything sticks out.

**Comment by fenryxo** [comment]
+1 from https://github.com/tiliado/nuvolaplayer/issues/224#issuecomment-223895704

**Comment by fenryxo** [comment]
It seems that Spotify's own JavaScript code sometimes fails. Since the track info parsing code is dependent on the Spotify's JavaScript API, metadata parsing also fails. It might be possible to switch to DOM document parsing to get the metadata as a workaround.
