### ISSUE TITLE
Nuvola Spotify App starts playing a second track

### ISSUE THREAD

**Issue by pyriand3r** [tiliado/nuvola-app-spotify#11]
Sometimes the Nuvola Spotify App starts playing a second track, so that two tracks are playing simultaniously. Hitting the pause-button in the Spotify UI stops the "official" playing track, playback of the second track can only be stopped by closing Nuvola.

Mentioned in:  #10 

The issue is difficult to reproduce and therefore to provide logs, i will try to give some when it happens again.

System: Arch Linux x86-64
Nuvola: 3.1.0+201605091422.e324991
Spotify-App: 2.1
Webkit Engine: WebKitGTK 2.12.2

**Comment by pyriand3r** [comment]
Lucky me, lucky you the bug was not far away. I started Nuvoly Spotify with debug on, playback of song was not recognized and a few minutes later a second song started. Here is the debug output:

https://gist.github.com/pyriand3r/ceadbf72f8315489c0e05e0ddd50a29f

Hopefully this helps. Window was minimized and i did not press any media hotkeys.

**Comment by pyriand3r** [comment]
Sorry for closing the ticket... Hit the wring button :(

**Comment by fenryxo** [comment]
When the issue doesn't occur, does the log still contain following line?

`Runner: https://d3jfuiz4ixupna.cloudfront.net/sdk/spotify.sdk.5.9.2-enc-feea156.min.js:27:1381: CONSOLE ERROR TypeError: null is not an object (evaluating 'player.getPlayerState')`

Does the issue occur also in Epiphany/GNOME Web browser?

**Comment by pyriand3r** [comment]
Atm Nuvola Spotify if running with debug on, no second track appeared until now but the song recognition is not working. The line appears in the debug output.

Haven't tried to use Spotify Web App in Epiphany so far, but i will give it a try.

**Comment by pyriand3r** [comment]
So, i have used spotify now for a whole day with epiphany and this behaviour did not appear.

**Comment by fenryxo** [comment]
Hello @pyriand3r. If you still use Nuvola 3.1, could you check whether the issue is still reproducible with the latest Diorite & Nuvola Player builds? There have been a few bug fixes. Thanks.

**Comment by pyriand3r** [comment]
Hi, sorry for the late reply... Haven't had this issue for some time now, so I would say it is fixed. ;)

So i close the issue.
