### ISSUE TITLE
flash player problem on linux

### ISSUE THREAD

**Issue by alanvbs** [tiliado/nuvola-app-spotify#17]
Hi. I started to use the nuvola-spotify player. However I run into some problems that I believe is related
to the flash player. After some interactions with the interface  (for instance changing tabs, close the player window) the player stop to work. Running the player with the the debug option activated  this type of message appears on the log.

```
Runner: https://xxxxxxxxxxx.cloudfront.net/sdk/spotify.sdk.5.9.6-enc-cf3c98c.min.js:9:4822: CONSOLE ERROR TypeError: _flashObject.getSWF().sp_playerState is not a function. (In '_flashObject.getSWF().sp_playerState(id)', '_flashObject.getSWF().sp_playerState' is undefined)
```
Also in the command line appears this message
```
Vector smash protection is enabled.
```

Using nuvola 3 on fedora 25

**Comment by fenryxo** [comment]
Closing in favour of tiliado/nuvolaplayer#278
