### ISSUE TITLE
doesn't start in Fedora 27

### ISSUE THREAD

**Issue by Kidlike** [tiliado/nuvola-app-spotify#25]
I used this guide for installation:

https://nuvola.tiliado.eu/nuvola/fedora/fc27/
https://nuvola.tiliado.eu/app/spotify/fedora/fc27/

When I try to run I get this:

```
$ flatpak run eu.tiliado.NuvolaAppSpotify
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "pk-gtk-module"
[0320/105652.104837:ERROR:widevine_loader.cc(252)] Widevine CDM registration failed; Missing manifest file /home/kidlike/.var/app/eu.tiliado.NuvolaAppSpotify/data/nuvolaruntime/apps_data/spotify/widevine/manifest.json
Runner: [WARNING Δ198868us CefGtk] WidevinePlugin.vala:29: WidevinePlugin not available: 1 Missing manifest file /home/kidlike/.var/app/eu.tiliado.NuvolaAppSpotify/data/nuvolaruntime/apps_data/spotify/widevine/manifest.json
Runner: [WARNING Δ000144us Nuvola] StartupCheck.vala:270: Failed requirements: Chromium[63] Feature[widevine]
Runner: [WARNING Δ000043us Nuvola] StartupCheck.vala:271: Unknown requirements: 
Runner: [WARNING Δ000034us Nuvola] StartupCheck.vala:281: Chromium: Failed to load Widevine plugin: Missing manifest file /home/kidlike/.var/app/eu.tiliado.NuvolaAppSpotify/data/nuvolaruntime/apps_data/spotify/widevine/manifest.json
Runner: [WARNING Δ000109us Nuvola] StartupWindow.vala:205: app-requirements-message: This web app requires certain technologies to function properly but these requirements have not been satisfied.

Contact your distributor to get assistance.
ATTENTION: default value of option force_s3tc_enable overridden by environment.
```

![screenshot from 2018-03-20 11-37-02](https://user-images.githubusercontent.com/5050182/37649737-0ace1596-2c33-11e8-846c-cda49339ea87.png)

After some investigation I found this issue:
```
$ pwd
/home/kidlike/.var/app/eu.tiliado.NuvolaAppSpotify/data/nuvolaruntime/apps_data/spotify/widevine
$ ll manifest.json 
lrwxrwxrwx 1 kidlike kidlike 26 Mar 20 10:50 manifest.json -> /app/lib/cef/manifest.json
```

**The `/app` folder in Fedora doesn't exist. If I'm not mistaken that's a MacOS thing.**

**Comment by fenryxo** [comment]
Hello @Kidlike. Thanks for reporting this issue. It seems that the `/app/lib/cef/manifest.json` file was accidentally removed during clean-up. I'll add it as soon as possible. 

> The `/app` folder in Fedora doesn't exist. If I'm not mistaken that's a MacOS thing.

The `/app` folder is Flatpak's thing.

**Comment by Kidlike** [comment]
Oh ok... cool :)

Is there a workaround that I could do until you publish the fix ?

**Comment by fenryxo** [comment]
Well, you could replace the `apps_data/spotify/widevine/manifest.json` symlink with real content, but I don't have that file with me right now.

**Comment by fenryxo** [comment]
It should be now fixed in stable builds. Could you run `flatpak update --system; flatpak update --user`?

**Comment by Kidlike** [comment]
Thanks works now :)
