### ISSUE TITLE
Spotify player not pulling data

### ISSUE THREAD

**Issue by hansenji** [tiliado/nuvola-app-spotify#3]
When I open spotify I get a blank screen with the icon.

When I press play I get this message.
Error during call of Nuvola.actions.emit: Function 'Nuvola.actions.emit' failed. file:///usr/share/nuvolaplayer3/web_apps/spotify/integrate.js:156: TypeError: undefined is not an object (evaluating 'this.spotifyPlayer.togglePlay')

The application might not function properly.

**Comment by fenryxo** [comment]
Hello @hansenji. This issue is tracked as tiliado/nuvolaplayer#82 and there is a workaround for the problem in that ticket.
