### ISSUE TITLE
Plugin Stopped working

### ISSUE THREAD

**Issue by pyriand3r** [tiliado/nuvola-app-spotify#4]
Hi there,
a few days ago the plugin stopped working for me. The spotify logo shows up but nothing else. I deleted the spotify.json config-file and everything else like cache etc. i could find... Any ideas? All other plugins are working as always.

Here is the startup log:

    [Runner:WARNING  GLib-GObject] g_object_set_property: construct property "local-storage-directory" for object 'WebKitWebContext' can't be set after construction
    [Worker:DEBUG    Nuvola] main.vala:201: Page 1 created for (null)
    [Worker:INFO     Nuvola] main.vala:212: Nuvola Issue #100 hotfix not enabled. https://github.com/tiliado/nuvolaplayer/issues/100
    [Runner:WARNING  Nuvola] FormatSupportCheck.vala:137: Too many Flash plugins have been found: 2
    [Worker:DEBUG    Nuvola] main.vala:125: Window object cleared: https://play.spotify.com/browse, 0x266d900, 0x2687410, 0x7f56a802f4b0
    https://d3jfuiz4ixupna.cloudfront.net/sdk/spotify.sdk.5.8.3-8be3a59.min.js:67:146: CONSOLE ERROR TypeError: undefined is not an object (evaluating 'h')

**Comment by thenyeguy** [comment]
Hi @pyriand3r. This is a known issue (tiliado/nuvolaplayer#82), you can find a workaround on that page.

**Comment by pyriand3r** [comment]
Oh well thank you! The workaround fixed it.
Thanks!
