### ISSUE TITLE
spotify webapp does not start

### ISSUE THREAD

**Issue by real-or-random** [tiliado/nuvola-app-spotify#9]
Fresh installation from git on Arch Linux.

Starting the player and pressing the play button to start the spotify webapp gives me:
https://gist.github.com/anonymous/d622ddd313d2e83ad339

The selection window disappears and nothing happens. The process is still running.

**Comment by fenryxo** [comment]
Hello @real-or-random. Thanks for taking the time to report your issue. I need more information to investigate it further:

* Version of Nuvola Player.
* Your desktop environment and its version.

See [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines) for details.

**Comment by real-or-random** [comment]
Well, I reinstalled and nuvola and it works now. No idea what went wrong, because it was a fresh installation. I've never used nuvola before.
